/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseToken
 */
export interface BaseToken {
    /**
     * 
     * @type {number}
     * @memberof BaseToken
     */
    decimals?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseToken
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseToken
     */
    subunit?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseToken
     */
    tickerSymbol?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseToken
     */
    unit?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BaseToken
     */
    useMetricPrefix?: boolean;
}

/**
 * Check if a given object implements the BaseToken interface.
 */
export function instanceOfBaseToken(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BaseTokenFromJSON(json: any): BaseToken {
    return BaseTokenFromJSONTyped(json, false);
}

export function BaseTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'decimals': !exists(json, 'Decimals') ? undefined : json['Decimals'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'subunit': !exists(json, 'Subunit') ? undefined : json['Subunit'],
        'tickerSymbol': !exists(json, 'TickerSymbol') ? undefined : json['TickerSymbol'],
        'unit': !exists(json, 'Unit') ? undefined : json['Unit'],
        'useMetricPrefix': !exists(json, 'UseMetricPrefix') ? undefined : json['UseMetricPrefix'],
    };
}

export function BaseTokenToJSON(value?: BaseToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Decimals': value.decimals,
        'Name': value.name,
        'Subunit': value.subunit,
        'TickerSymbol': value.tickerSymbol,
        'Unit': value.unit,
        'UseMetricPrefix': value.useMetricPrefix,
    };
}

