/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.4.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Blob } from './Blob';
import {
    BlobFromJSON,
    BlobFromJSONTyped,
    BlobToJSON,
} from './Blob';

/**
 * 
 * @export
 * @interface BlobListResponse
 */
export interface BlobListResponse {
    /**
     * 
     * @type {Array<Blob>}
     * @memberof BlobListResponse
     */
    blobs?: Array<Blob>;
}

/**
 * Check if a given object implements the BlobListResponse interface.
 */
export function instanceOfBlobListResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BlobListResponseFromJSON(json: any): BlobListResponse {
    return BlobListResponseFromJSONTyped(json, false);
}

export function BlobListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlobListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blobs': !exists(json, 'Blobs') ? undefined : ((json['Blobs'] as Array<any>).map(BlobFromJSON)),
    };
}

export function BlobListResponseToJSON(value?: BlobListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Blobs': value.blobs === undefined ? undefined : ((value.blobs as Array<any>).map(BlobToJSON)),
    };
}

