/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.4.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockInfoResponse
 */
export interface BlockInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof BlockInfoResponse
     */
    anchorTransactionId?: string;
    /**
     * 
     * @type {number}
     * @memberof BlockInfoResponse
     */
    blockIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof BlockInfoResponse
     */
    gasBurned?: number;
    /**
     * 
     * @type {number}
     * @memberof BlockInfoResponse
     */
    gasFeeCharged?: number;
    /**
     * 
     * @type {string}
     * @memberof BlockInfoResponse
     */
    l1CommitmentHash?: string;
    /**
     * 
     * @type {number}
     * @memberof BlockInfoResponse
     */
    numOffLedgerRequests?: number;
    /**
     * 
     * @type {number}
     * @memberof BlockInfoResponse
     */
    numSuccessfulRequests?: number;
    /**
     * 
     * @type {string}
     * @memberof BlockInfoResponse
     */
    previousL1CommitmentHash?: string;
    /**
     * 
     * @type {Date}
     * @memberof BlockInfoResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof BlockInfoResponse
     */
    totalBaseTokensInL2Accounts?: number;
    /**
     * 
     * @type {number}
     * @memberof BlockInfoResponse
     */
    totalRequests?: number;
    /**
     * 
     * @type {number}
     * @memberof BlockInfoResponse
     */
    totalStorageDeposit?: number;
    /**
     * 
     * @type {string}
     * @memberof BlockInfoResponse
     */
    transactionSubEssenceHash?: string;
}

/**
 * Check if a given object implements the BlockInfoResponse interface.
 */
export function instanceOfBlockInfoResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BlockInfoResponseFromJSON(json: any): BlockInfoResponse {
    return BlockInfoResponseFromJSONTyped(json, false);
}

export function BlockInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'anchorTransactionId': !exists(json, 'anchorTransactionId') ? undefined : json['anchorTransactionId'],
        'blockIndex': !exists(json, 'blockIndex') ? undefined : json['blockIndex'],
        'gasBurned': !exists(json, 'gasBurned') ? undefined : json['gasBurned'],
        'gasFeeCharged': !exists(json, 'gasFeeCharged') ? undefined : json['gasFeeCharged'],
        'l1CommitmentHash': !exists(json, 'l1CommitmentHash') ? undefined : json['l1CommitmentHash'],
        'numOffLedgerRequests': !exists(json, 'numOffLedgerRequests') ? undefined : json['numOffLedgerRequests'],
        'numSuccessfulRequests': !exists(json, 'numSuccessfulRequests') ? undefined : json['numSuccessfulRequests'],
        'previousL1CommitmentHash': !exists(json, 'previousL1CommitmentHash') ? undefined : json['previousL1CommitmentHash'],
        'timestamp': !exists(json, 'timestamp') ? undefined : (new Date(json['timestamp'])),
        'totalBaseTokensInL2Accounts': !exists(json, 'totalBaseTokensInL2Accounts') ? undefined : json['totalBaseTokensInL2Accounts'],
        'totalRequests': !exists(json, 'totalRequests') ? undefined : json['totalRequests'],
        'totalStorageDeposit': !exists(json, 'totalStorageDeposit') ? undefined : json['totalStorageDeposit'],
        'transactionSubEssenceHash': !exists(json, 'transactionSubEssenceHash') ? undefined : json['transactionSubEssenceHash'],
    };
}

export function BlockInfoResponseToJSON(value?: BlockInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'anchorTransactionId': value.anchorTransactionId,
        'blockIndex': value.blockIndex,
        'gasBurned': value.gasBurned,
        'gasFeeCharged': value.gasFeeCharged,
        'l1CommitmentHash': value.l1CommitmentHash,
        'numOffLedgerRequests': value.numOffLedgerRequests,
        'numSuccessfulRequests': value.numSuccessfulRequests,
        'previousL1CommitmentHash': value.previousL1CommitmentHash,
        'timestamp': value.timestamp === undefined ? undefined : (value.timestamp.toISOString()),
        'totalBaseTokensInL2Accounts': value.totalBaseTokensInL2Accounts,
        'totalRequests': value.totalRequests,
        'totalStorageDeposit': value.totalStorageDeposit,
        'transactionSubEssenceHash': value.transactionSubEssenceHash,
    };
}

