/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssetsResponse } from './AssetsResponse';
import {
    AssetsResponseFromJSON,
    AssetsResponseFromJSONTyped,
    AssetsResponseToJSON,
} from './AssetsResponse';

/**
 * 
 * @export
 * @interface FoundryOutputResponse
 */
export interface FoundryOutputResponse {
    /**
     * 
     * @type {string}
     * @memberof FoundryOutputResponse
     */
    foundryID?: string;
    /**
     * 
     * @type {AssetsResponse}
     * @memberof FoundryOutputResponse
     */
    token?: AssetsResponse;
}

/**
 * Check if a given object implements the FoundryOutputResponse interface.
 */
export function instanceOfFoundryOutputResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FoundryOutputResponseFromJSON(json: any): FoundryOutputResponse {
    return FoundryOutputResponseFromJSONTyped(json, false);
}

export function FoundryOutputResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoundryOutputResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'foundryID': !exists(json, 'FoundryID') ? undefined : json['FoundryID'],
        'token': !exists(json, 'Token') ? undefined : AssetsResponseFromJSON(json['Token']),
    };
}

export function FoundryOutputResponseToJSON(value?: FoundryOutputResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'FoundryID': value.foundryID,
        'Token': AssetsResponseToJSON(value.token),
    };
}

