/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Output } from './Output';
import {
    OutputFromJSON,
    OutputFromJSONTyped,
    OutputToJSON,
} from './Output';

/**
 * 
 * @export
 * @interface InStateOutput
 */
export interface InStateOutput {
    /**
     * 
     * @type {Output}
     * @memberof InStateOutput
     */
    output?: Output;
    /**
     * 
     * @type {string}
     * @memberof InStateOutput
     */
    outputID?: string;
}

/**
 * Check if a given object implements the InStateOutput interface.
 */
export function instanceOfInStateOutput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InStateOutputFromJSON(json: any): InStateOutput {
    return InStateOutputFromJSONTyped(json, false);
}

export function InStateOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): InStateOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'output': !exists(json, 'Output') ? undefined : OutputFromJSON(json['Output']),
        'outputID': !exists(json, 'OutputID') ? undefined : json['OutputID'],
    };
}

export function InStateOutputToJSON(value?: InStateOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Output': OutputToJSON(value.output),
        'OutputID': value.outputID,
    };
}

