/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NativeTokenIDRegistryResponse
 */
export interface NativeTokenIDRegistryResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof NativeTokenIDRegistryResponse
     */
    nativeTokenRegistryIDs?: Array<string>;
}

/**
 * Check if a given object implements the NativeTokenIDRegistryResponse interface.
 */
export function instanceOfNativeTokenIDRegistryResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NativeTokenIDRegistryResponseFromJSON(json: any): NativeTokenIDRegistryResponse {
    return NativeTokenIDRegistryResponseFromJSONTyped(json, false);
}

export function NativeTokenIDRegistryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NativeTokenIDRegistryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nativeTokenRegistryIDs': !exists(json, 'NativeTokenRegistryIDs') ? undefined : json['NativeTokenRegistryIDs'],
    };
}

export function NativeTokenIDRegistryResponseToJSON(value?: NativeTokenIDRegistryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NativeTokenRegistryIDs': value.nativeTokenRegistryIDs,
    };
}

