/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OffLedgerRequest
 */
export interface OffLedgerRequest {
    /**
     * The chain id
     * @type {string}
     * @memberof OffLedgerRequest
     */
    chainID?: string;
    /**
     * Offledger Request (Hex)
     * @type {string}
     * @memberof OffLedgerRequest
     */
    request?: string;
}

/**
 * Check if a given object implements the OffLedgerRequest interface.
 */
export function instanceOfOffLedgerRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OffLedgerRequestFromJSON(json: any): OffLedgerRequest {
    return OffLedgerRequestFromJSONTyped(json, false);
}

export function OffLedgerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OffLedgerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chainID': !exists(json, 'ChainID') ? undefined : json['ChainID'],
        'request': !exists(json, 'Request') ? undefined : json['Request'],
    };
}

export function OffLedgerRequestToJSON(value?: OffLedgerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ChainID': value.chainID,
        'Request': value.request,
    };
}

