/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
} from './Transaction';

/**
 * 
 * @export
 * @interface TransactionIDMetricItem
 */
export interface TransactionIDMetricItem {
    /**
     * 
     * @type {Transaction}
     * @memberof TransactionIDMetricItem
     */
    lastMessage?: Transaction;
    /**
     * 
     * @type {number}
     * @memberof TransactionIDMetricItem
     */
    messages?: number;
    /**
     * 
     * @type {Date}
     * @memberof TransactionIDMetricItem
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the TransactionIDMetricItem interface.
 */
export function instanceOfTransactionIDMetricItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TransactionIDMetricItemFromJSON(json: any): TransactionIDMetricItem {
    return TransactionIDMetricItemFromJSONTyped(json, false);
}

export function TransactionIDMetricItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionIDMetricItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastMessage': !exists(json, 'LastMessage') ? undefined : TransactionFromJSON(json['LastMessage']),
        'messages': !exists(json, 'Messages') ? undefined : json['Messages'],
        'timestamp': !exists(json, 'Timestamp') ? undefined : (new Date(json['Timestamp'])),
    };
}

export function TransactionIDMetricItemToJSON(value?: TransactionIDMetricItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'LastMessage': TransactionToJSON(value.lastMessage),
        'Messages': value.messages,
        'Timestamp': value.timestamp === undefined ? undefined : (value.timestamp.toISOString()),
    };
}

