/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TxInclusionStateMsg
 */
export interface TxInclusionStateMsg {
    /**
     * 
     * @type {string}
     * @memberof TxInclusionStateMsg
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof TxInclusionStateMsg
     */
    transactionID?: string;
}

/**
 * Check if a given object implements the TxInclusionStateMsg interface.
 */
export function instanceOfTxInclusionStateMsg(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TxInclusionStateMsgFromJSON(json: any): TxInclusionStateMsg {
    return TxInclusionStateMsgFromJSONTyped(json, false);
}

export function TxInclusionStateMsgFromJSONTyped(json: any, ignoreDiscriminator: boolean): TxInclusionStateMsg {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'state': !exists(json, 'State') ? undefined : json['State'],
        'transactionID': !exists(json, 'TransactionID') ? undefined : json['TransactionID'],
    };
}

export function TxInclusionStateMsgToJSON(value?: TxInclusionStateMsg | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'State': value.state,
        'TransactionID': value.transactionID,
    };
}

