/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserPermissionsRequest
 */
export interface UpdateUserPermissionsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateUserPermissionsRequest
     */
    permissions?: Array<string>;
}

/**
 * Check if a given object implements the UpdateUserPermissionsRequest interface.
 */
export function instanceOfUpdateUserPermissionsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateUserPermissionsRequestFromJSON(json: any): UpdateUserPermissionsRequest {
    return UpdateUserPermissionsRequestFromJSONTyped(json, false);
}

export function UpdateUserPermissionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserPermissionsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'permissions': !exists(json, 'Permissions') ? undefined : json['Permissions'],
    };
}

export function UpdateUserPermissionsRequestToJSON(value?: UpdateUserPermissionsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Permissions': value.permissions,
    };
}

