/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.4.0-alpha.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OutputID } from './OutputID';
import {
    OutputIDFromJSON,
    OutputIDFromJSONTyped,
    OutputIDToJSON,
} from './OutputID';

/**
 * 
 * @export
 * @interface UTXOInputMetricItem
 */
export interface UTXOInputMetricItem {
    /**
     * 
     * @type {OutputID}
     * @memberof UTXOInputMetricItem
     */
    lastMessage?: OutputID;
    /**
     * 
     * @type {number}
     * @memberof UTXOInputMetricItem
     */
    messages?: number;
    /**
     * 
     * @type {Date}
     * @memberof UTXOInputMetricItem
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the UTXOInputMetricItem interface.
 */
export function instanceOfUTXOInputMetricItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UTXOInputMetricItemFromJSON(json: any): UTXOInputMetricItem {
    return UTXOInputMetricItemFromJSONTyped(json, false);
}

export function UTXOInputMetricItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UTXOInputMetricItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastMessage': !exists(json, 'lastMessage') ? undefined : OutputIDFromJSON(json['lastMessage']),
        'messages': !exists(json, 'messages') ? undefined : json['messages'],
        'timestamp': !exists(json, 'timestamp') ? undefined : (new Date(json['timestamp'])),
    };
}

export function UTXOInputMetricItemToJSON(value?: UTXOInputMetricItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastMessage': OutputIDToJSON(value.lastMessage),
        'messages': value.messages,
        'timestamp': value.timestamp === undefined ? undefined : (value.timestamp.toISOString()),
    };
}

