/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 123
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountNonceResponse
 */
export interface AccountNonceResponse {
    /**
     * 
     * @type {number}
     * @memberof AccountNonceResponse
     */
    nonce?: number;
}

/**
 * Check if a given object implements the AccountNonceResponse interface.
 */
export function instanceOfAccountNonceResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccountNonceResponseFromJSON(json: any): AccountNonceResponse {
    return AccountNonceResponseFromJSONTyped(json, false);
}

export function AccountNonceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountNonceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nonce': !exists(json, 'nonce') ? undefined : json['nonce'],
    };
}

export function AccountNonceResponseToJSON(value?: AccountNonceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nonce': value.nonce,
    };
}

