/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthInfoModel
 */
export interface AuthInfoModel {
    /**
     * JWT only
     * @type {string}
     * @memberof AuthInfoModel
     */
    authURL: string;
    /**
     * 
     * @type {string}
     * @memberof AuthInfoModel
     */
    scheme: string;
}

/**
 * Check if a given object implements the AuthInfoModel interface.
 */
export function instanceOfAuthInfoModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "authURL" in value;
    isInstance = isInstance && "scheme" in value;

    return isInstance;
}

export function AuthInfoModelFromJSON(json: any): AuthInfoModel {
    return AuthInfoModelFromJSONTyped(json, false);
}

export function AuthInfoModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthInfoModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authURL': json['authURL'],
        'scheme': json['scheme'],
    };
}

export function AuthInfoModelToJSON(value?: AuthInfoModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authURL': value.authURL,
        'scheme': value.scheme,
    };
}

