/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlobInfoResponse
 */
export interface BlobInfoResponse {
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof BlobInfoResponse
     */
    fields: { [key: string]: number; };
}

/**
 * Check if a given object implements the BlobInfoResponse interface.
 */
export function instanceOfBlobInfoResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fields" in value;

    return isInstance;
}

export function BlobInfoResponseFromJSON(json: any): BlobInfoResponse {
    return BlobInfoResponseFromJSONTyped(json, false);
}

export function BlobInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlobInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fields': json['fields'],
    };
}

export function BlobInfoResponseToJSON(value?: BlobInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fields': value.fields,
    };
}

