/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockReceiptError
 */
export interface BlockReceiptError {
    /**
     * 
     * @type {string}
     * @memberof BlockReceiptError
     */
    errorMessage: string;
    /**
     * 
     * @type {string}
     * @memberof BlockReceiptError
     */
    hash: string;
}

/**
 * Check if a given object implements the BlockReceiptError interface.
 */
export function instanceOfBlockReceiptError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "errorMessage" in value;
    isInstance = isInstance && "hash" in value;

    return isInstance;
}

export function BlockReceiptErrorFromJSON(json: any): BlockReceiptError {
    return BlockReceiptErrorFromJSONTyped(json, false);
}

export function BlockReceiptErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockReceiptError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorMessage': json['errorMessage'],
        'hash': json['hash'],
    };
}

export function BlockReceiptErrorToJSON(value?: BlockReceiptError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': value.errorMessage,
        'hash': value.hash,
    };
}

