/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BurnRecord } from './BurnRecord';
import {
    BurnRecordFromJSON,
    BurnRecordFromJSONTyped,
    BurnRecordToJSON,
} from './BurnRecord';

/**
 * 
 * @export
 * @interface BurnLog
 */
export interface BurnLog {
    /**
     * 
     * @type {Array<BurnRecord>}
     * @memberof BurnLog
     */
    records: Array<BurnRecord>;
}

/**
 * Check if a given object implements the BurnLog interface.
 */
export function instanceOfBurnLog(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "records" in value;

    return isInstance;
}

export function BurnLogFromJSON(json: any): BurnLog {
    return BurnLogFromJSONTyped(json, false);
}

export function BurnLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): BurnLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'records': ((json['records'] as Array<any>).map(BurnRecordFromJSON)),
    };
}

export function BurnLogToJSON(value?: BurnLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'records': ((value.records as Array<any>).map(BurnRecordToJSON)),
    };
}

