/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CallTarget
 */
export interface CallTarget {
    /**
     * The contract name as HName (Hex)
     * @type {string}
     * @memberof CallTarget
     */
    contractHName: string;
    /**
     * The function name as HName (Hex)
     * @type {string}
     * @memberof CallTarget
     */
    functionHName: string;
}

/**
 * Check if a given object implements the CallTarget interface.
 */
export function instanceOfCallTarget(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contractHName" in value;
    isInstance = isInstance && "functionHName" in value;

    return isInstance;
}

export function CallTargetFromJSON(json: any): CallTarget {
    return CallTargetFromJSONTyped(json, false);
}

export function CallTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallTarget {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contractHName': json['contractHName'],
        'functionHName': json['functionHName'],
    };
}

export function CallTargetToJSON(value?: CallTarget | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contractHName': value.contractHName,
        'functionHName': value.functionHName,
    };
}

