/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 123
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CallTarget
 */
export interface CallTarget {
    /**
     * 
     * @type {number}
     * @memberof CallTarget
     */
    contract?: number;
    /**
     * 
     * @type {number}
     * @memberof CallTarget
     */
    entryPoint?: number;
}

/**
 * Check if a given object implements the CallTarget interface.
 */
export function instanceOfCallTarget(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CallTargetFromJSON(json: any): CallTarget {
    return CallTargetFromJSONTyped(json, false);
}

export function CallTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallTarget {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contract': !exists(json, 'Contract') ? undefined : json['Contract'],
        'entryPoint': !exists(json, 'EntryPoint') ? undefined : json['EntryPoint'],
    };
}

export function CallTargetToJSON(value?: CallTarget | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Contract': value.contract,
        'EntryPoint': value.entryPoint,
    };
}

