/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FeePolicy } from './FeePolicy';
import {
    FeePolicyFromJSON,
    FeePolicyFromJSONTyped,
    FeePolicyToJSON,
} from './FeePolicy';
import type { Limits } from './Limits';
import {
    LimitsFromJSON,
    LimitsFromJSONTyped,
    LimitsToJSON,
} from './Limits';

/**
 * 
 * @export
 * @interface ChainInfoResponse
 */
export interface ChainInfoResponse {
    /**
     * ChainID (Bech32-encoded).
     * @type {string}
     * @memberof ChainInfoResponse
     */
    chainID: string;
    /**
     * The chain owner address (Bech32-encoded).
     * @type {string}
     * @memberof ChainInfoResponse
     */
    chainOwnerId: string;
    /**
     * (base64) Optional extra metadata that is appended to the L1 AliasOutput
     * @type {string}
     * @memberof ChainInfoResponse
     */
    customMetadata?: string;
    /**
     * The EVM chain ID
     * @type {number}
     * @memberof ChainInfoResponse
     */
    evmChainId: number;
    /**
     * 
     * @type {FeePolicy}
     * @memberof ChainInfoResponse
     */
    gasFeePolicy: FeePolicy;
    /**
     * 
     * @type {Limits}
     * @memberof ChainInfoResponse
     */
    gasLimits: Limits;
    /**
     * Whether or not the chain is active.
     * @type {boolean}
     * @memberof ChainInfoResponse
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the ChainInfoResponse interface.
 */
export function instanceOfChainInfoResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chainID" in value;
    isInstance = isInstance && "chainOwnerId" in value;
    isInstance = isInstance && "evmChainId" in value;
    isInstance = isInstance && "gasFeePolicy" in value;
    isInstance = isInstance && "gasLimits" in value;
    isInstance = isInstance && "isActive" in value;

    return isInstance;
}

export function ChainInfoResponseFromJSON(json: any): ChainInfoResponse {
    return ChainInfoResponseFromJSONTyped(json, false);
}

export function ChainInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chainID': json['chainID'],
        'chainOwnerId': json['chainOwnerId'],
        'customMetadata': !exists(json, 'customMetadata') ? undefined : json['customMetadata'],
        'evmChainId': json['evmChainId'],
        'gasFeePolicy': FeePolicyFromJSON(json['gasFeePolicy']),
        'gasLimits': LimitsFromJSON(json['gasLimits']),
        'isActive': json['isActive'],
    };
}

export function ChainInfoResponseToJSON(value?: ChainInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chainID': value.chainID,
        'chainOwnerId': value.chainOwnerId,
        'customMetadata': value.customMetadata,
        'evmChainId': value.evmChainId,
        'gasFeePolicy': FeePolicyToJSON(value.gasFeePolicy),
        'gasLimits': LimitsToJSON(value.gasLimits),
        'isActive': value.isActive,
    };
}

