/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.4.0-alpha.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChainRecord
 */
export interface ChainRecord {
    /**
     * 
     * @type {Array<string>}
     * @memberof ChainRecord
     */
    accessNodes?: Array<string>;
    /**
     * Whether or not the chain is active
     * @type {boolean}
     * @memberof ChainRecord
     */
    active?: boolean;
    /**
     * ChainID (bech32)
     * @type {string}
     * @memberof ChainRecord
     */
    chainId?: string;
}

/**
 * Check if a given object implements the ChainRecord interface.
 */
export function instanceOfChainRecord(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainRecordFromJSON(json: any): ChainRecord {
    return ChainRecordFromJSONTyped(json, false);
}

export function ChainRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessNodes': !exists(json, 'accessNodes') ? undefined : json['accessNodes'],
        'active': !exists(json, 'active') ? undefined : json['active'],
        'chainId': !exists(json, 'chainId') ? undefined : json['chainId'],
    };
}

export function ChainRecordToJSON(value?: ChainRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessNodes': value.accessNodes,
        'active': value.active,
        'chainId': value.chainId,
    };
}

