/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChainRecord
 */
export interface ChainRecord {
    /**
     * 
     * @type {Array<string>}
     * @memberof ChainRecord
     */
    accessNodes: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ChainRecord
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the ChainRecord interface.
 */
export function instanceOfChainRecord(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessNodes" in value;
    isInstance = isInstance && "isActive" in value;

    return isInstance;
}

export function ChainRecordFromJSON(json: any): ChainRecord {
    return ChainRecordFromJSONTyped(json, false);
}

export function ChainRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessNodes': json['accessNodes'],
        'isActive': json['isActive'],
    };
}

export function ChainRecordToJSON(value?: ChainRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessNodes': value.accessNodes,
        'isActive': value.isActive,
    };
}

