/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 123
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AliasOutputMetricItem } from './AliasOutputMetricItem';
import {
    AliasOutputMetricItemFromJSON,
    AliasOutputMetricItemFromJSONTyped,
    AliasOutputMetricItemToJSON,
} from './AliasOutputMetricItem';
import type { InOutputMetricItem } from './InOutputMetricItem';
import {
    InOutputMetricItemFromJSON,
    InOutputMetricItemFromJSONTyped,
    InOutputMetricItemToJSON,
} from './InOutputMetricItem';
import type { InStateOutputMetricItem } from './InStateOutputMetricItem';
import {
    InStateOutputMetricItemFromJSON,
    InStateOutputMetricItemFromJSONTyped,
    InStateOutputMetricItemToJSON,
} from './InStateOutputMetricItem';
import type { InterfaceMetricItem } from './InterfaceMetricItem';
import {
    InterfaceMetricItemFromJSON,
    InterfaceMetricItemFromJSONTyped,
    InterfaceMetricItemToJSON,
} from './InterfaceMetricItem';
import type { OnLedgerRequestMetricItem } from './OnLedgerRequestMetricItem';
import {
    OnLedgerRequestMetricItemFromJSON,
    OnLedgerRequestMetricItemFromJSONTyped,
    OnLedgerRequestMetricItemToJSON,
} from './OnLedgerRequestMetricItem';
import type { TransactionIDMetricItem } from './TransactionIDMetricItem';
import {
    TransactionIDMetricItemFromJSON,
    TransactionIDMetricItemFromJSONTyped,
    TransactionIDMetricItemToJSON,
} from './TransactionIDMetricItem';
import type { TransactionMetricItem } from './TransactionMetricItem';
import {
    TransactionMetricItemFromJSON,
    TransactionMetricItemFromJSONTyped,
    TransactionMetricItemToJSON,
} from './TransactionMetricItem';
import type { TxInclusionStateMsgMetricItem } from './TxInclusionStateMsgMetricItem';
import {
    TxInclusionStateMsgMetricItemFromJSON,
    TxInclusionStateMsgMetricItemFromJSONTyped,
    TxInclusionStateMsgMetricItemToJSON,
} from './TxInclusionStateMsgMetricItem';
import type { UTXOInputMetricItem } from './UTXOInputMetricItem';
import {
    UTXOInputMetricItemFromJSON,
    UTXOInputMetricItemFromJSONTyped,
    UTXOInputMetricItemToJSON,
} from './UTXOInputMetricItem';

/**
 * 
 * @export
 * @interface ChainMetrics
 */
export interface ChainMetrics {
    /**
     * 
     * @type {AliasOutputMetricItem}
     * @memberof ChainMetrics
     */
    inAliasOutput?: AliasOutputMetricItem;
    /**
     * 
     * @type {OnLedgerRequestMetricItem}
     * @memberof ChainMetrics
     */
    inOnLedgerRequest?: OnLedgerRequestMetricItem;
    /**
     * 
     * @type {InOutputMetricItem}
     * @memberof ChainMetrics
     */
    inOutput?: InOutputMetricItem;
    /**
     * 
     * @type {InStateOutputMetricItem}
     * @memberof ChainMetrics
     */
    inStateOutput?: InStateOutputMetricItem;
    /**
     * 
     * @type {TxInclusionStateMsgMetricItem}
     * @memberof ChainMetrics
     */
    inTxInclusionState?: TxInclusionStateMsgMetricItem;
    /**
     * 
     * @type {TransactionMetricItem}
     * @memberof ChainMetrics
     */
    outPublishGovernanceTransaction?: TransactionMetricItem;
    /**
     * 
     * @type {InterfaceMetricItem}
     * @memberof ChainMetrics
     */
    outPullLatestOutput?: InterfaceMetricItem;
    /**
     * 
     * @type {UTXOInputMetricItem}
     * @memberof ChainMetrics
     */
    outPullOutputByID?: UTXOInputMetricItem;
    /**
     * 
     * @type {TransactionIDMetricItem}
     * @memberof ChainMetrics
     */
    outPullTxInclusionState?: TransactionIDMetricItem;
}

/**
 * Check if a given object implements the ChainMetrics interface.
 */
export function instanceOfChainMetrics(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainMetricsFromJSON(json: any): ChainMetrics {
    return ChainMetricsFromJSONTyped(json, false);
}

export function ChainMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainMetrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inAliasOutput': !exists(json, 'inAliasOutput') ? undefined : AliasOutputMetricItemFromJSON(json['inAliasOutput']),
        'inOnLedgerRequest': !exists(json, 'inOnLedgerRequest') ? undefined : OnLedgerRequestMetricItemFromJSON(json['inOnLedgerRequest']),
        'inOutput': !exists(json, 'inOutput') ? undefined : InOutputMetricItemFromJSON(json['inOutput']),
        'inStateOutput': !exists(json, 'inStateOutput') ? undefined : InStateOutputMetricItemFromJSON(json['inStateOutput']),
        'inTxInclusionState': !exists(json, 'inTxInclusionState') ? undefined : TxInclusionStateMsgMetricItemFromJSON(json['inTxInclusionState']),
        'outPublishGovernanceTransaction': !exists(json, 'outPublishGovernanceTransaction') ? undefined : TransactionMetricItemFromJSON(json['outPublishGovernanceTransaction']),
        'outPullLatestOutput': !exists(json, 'outPullLatestOutput') ? undefined : InterfaceMetricItemFromJSON(json['outPullLatestOutput']),
        'outPullOutputByID': !exists(json, 'outPullOutputByID') ? undefined : UTXOInputMetricItemFromJSON(json['outPullOutputByID']),
        'outPullTxInclusionState': !exists(json, 'outPullTxInclusionState') ? undefined : TransactionIDMetricItemFromJSON(json['outPullTxInclusionState']),
    };
}

export function ChainMetricsToJSON(value?: ChainMetrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'inAliasOutput': AliasOutputMetricItemToJSON(value.inAliasOutput),
        'inOnLedgerRequest': OnLedgerRequestMetricItemToJSON(value.inOnLedgerRequest),
        'inOutput': InOutputMetricItemToJSON(value.inOutput),
        'inStateOutput': InStateOutputMetricItemToJSON(value.inStateOutput),
        'inTxInclusionState': TxInclusionStateMsgMetricItemToJSON(value.inTxInclusionState),
        'outPublishGovernanceTransaction': TransactionMetricItemToJSON(value.outPublishGovernanceTransaction),
        'outPullLatestOutput': InterfaceMetricItemToJSON(value.outPullLatestOutput),
        'outPullOutputByID': UTXOInputMetricItemToJSON(value.outPullOutputByID),
        'outPullTxInclusionState': TransactionIDMetricItemToJSON(value.outPullTxInclusionState),
    };
}

