/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.4.0-alpha.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GasFeePolicy
 */
export interface GasFeePolicy {
    /**
     * The gas fee token id. Empty if base token.
     * @type {string}
     * @memberof GasFeePolicy
     */
    gasFeeTokenId?: string;
    /**
     * The amount of gas per token.
     * @type {number}
     * @memberof GasFeePolicy
     */
    gasPerToken?: number;
    /**
     * The validator fee share.
     * @type {number}
     * @memberof GasFeePolicy
     */
    validatorFeeShare?: number;
}

/**
 * Check if a given object implements the GasFeePolicy interface.
 */
export function instanceOfGasFeePolicy(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GasFeePolicyFromJSON(json: any): GasFeePolicy {
    return GasFeePolicyFromJSONTyped(json, false);
}

export function GasFeePolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GasFeePolicy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gasFeeTokenId': !exists(json, 'gasFeeTokenId') ? undefined : json['gasFeeTokenId'],
        'gasPerToken': !exists(json, 'gasPerToken') ? undefined : json['gasPerToken'],
        'validatorFeeShare': !exists(json, 'validatorFeeShare') ? undefined : json['validatorFeeShare'],
    };
}

export function GasFeePolicyToJSON(value?: GasFeePolicy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gasFeeTokenId': value.gasFeeTokenId,
        'gasPerToken': value.gasPerToken,
        'validatorFeeShare': value.validatorFeeShare,
    };
}

