/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Ratio32 } from './Ratio32';
import {
    Ratio32FromJSON,
    Ratio32FromJSONTyped,
    Ratio32ToJSON,
} from './Ratio32';

/**
 * 
 * @export
 * @interface GasFeePolicy
 */
export interface GasFeePolicy {
    /**
     * 
     * @type {Ratio32}
     * @memberof GasFeePolicy
     */
    evmGasRatio: Ratio32;
    /**
     * 
     * @type {Ratio32}
     * @memberof GasFeePolicy
     */
    gasPerToken: Ratio32;
    /**
     * The validator fee share.
     * @type {number}
     * @memberof GasFeePolicy
     */
    validatorFeeShare: number;
}

/**
 * Check if a given object implements the GasFeePolicy interface.
 */
export function instanceOfGasFeePolicy(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "evmGasRatio" in value;
    isInstance = isInstance && "gasPerToken" in value;
    isInstance = isInstance && "validatorFeeShare" in value;

    return isInstance;
}

export function GasFeePolicyFromJSON(json: any): GasFeePolicy {
    return GasFeePolicyFromJSONTyped(json, false);
}

export function GasFeePolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GasFeePolicy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'evmGasRatio': Ratio32FromJSON(json['evmGasRatio']),
        'gasPerToken': Ratio32FromJSON(json['gasPerToken']),
        'validatorFeeShare': json['validatorFeeShare'],
    };
}

export function GasFeePolicyToJSON(value?: GasFeePolicy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'evmGasRatio': Ratio32ToJSON(value.evmGasRatio),
        'gasPerToken': Ratio32ToJSON(value.gasPerToken),
        'validatorFeeShare': value.validatorFeeShare,
    };
}

