/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Item } from './Item';
import {
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
} from './Item';

/**
 * 
 * @export
 * @interface JSONDict
 */
export interface JSONDict {
    /**
     * 
     * @type {Array<Item>}
     * @memberof JSONDict
     */
    items?: Array<Item>;
}

/**
 * Check if a given object implements the JSONDict interface.
 */
export function instanceOfJSONDict(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JSONDictFromJSON(json: any): JSONDict {
    return JSONDictFromJSONTyped(json, false);
}

export function JSONDictFromJSONTyped(json: any, ignoreDiscriminator: boolean): JSONDict {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'Items') ? undefined : ((json['Items'] as Array<any>).map(ItemFromJSON)),
    };
}

export function JSONDictToJSON(value?: JSONDict | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Items': value.items === undefined ? undefined : ((value.items as Array<any>).map(ItemToJSON)),
    };
}

