/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MilestoneInfo } from './MilestoneInfo';
import {
    MilestoneInfoFromJSON,
    MilestoneInfoFromJSONTyped,
    MilestoneInfoToJSON,
} from './MilestoneInfo';

/**
 * 
 * @export
 * @interface MilestoneMetricItem
 */
export interface MilestoneMetricItem {
    /**
     * 
     * @type {MilestoneInfo}
     * @memberof MilestoneMetricItem
     */
    lastMessage: MilestoneInfo;
    /**
     * 
     * @type {number}
     * @memberof MilestoneMetricItem
     */
    messages: number;
    /**
     * 
     * @type {Date}
     * @memberof MilestoneMetricItem
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the MilestoneMetricItem interface.
 */
export function instanceOfMilestoneMetricItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lastMessage" in value;
    isInstance = isInstance && "messages" in value;
    isInstance = isInstance && "timestamp" in value;

    return isInstance;
}

export function MilestoneMetricItemFromJSON(json: any): MilestoneMetricItem {
    return MilestoneMetricItemFromJSONTyped(json, false);
}

export function MilestoneMetricItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MilestoneMetricItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastMessage': MilestoneInfoFromJSON(json['lastMessage']),
        'messages': json['messages'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function MilestoneMetricItemToJSON(value?: MilestoneMetricItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastMessage': MilestoneInfoToJSON(value.lastMessage),
        'messages': value.messages,
        'timestamp': (value.timestamp.toISOString()),
    };
}

