/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NativeToken
 */
export interface NativeToken {
    /**
     * 
     * @type {string}
     * @memberof NativeToken
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof NativeToken
     */
    id: string;
}

/**
 * Check if a given object implements the NativeToken interface.
 */
export function instanceOfNativeToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function NativeTokenFromJSON(json: any): NativeToken {
    return NativeTokenFromJSONTyped(json, false);
}

export function NativeTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): NativeToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'id': json['id'],
    };
}

export function NativeTokenToJSON(value?: NativeToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'id': value.id,
    };
}

