/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeOwnerCertificateResponse
 */
export interface NodeOwnerCertificateResponse {
    /**
     * Certificate stating the ownership. (Hex)
     * @type {string}
     * @memberof NodeOwnerCertificateResponse
     */
    certificate: string;
}

/**
 * Check if a given object implements the NodeOwnerCertificateResponse interface.
 */
export function instanceOfNodeOwnerCertificateResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "certificate" in value;

    return isInstance;
}

export function NodeOwnerCertificateResponseFromJSON(json: any): NodeOwnerCertificateResponse {
    return NodeOwnerCertificateResponseFromJSONTyped(json, false);
}

export function NodeOwnerCertificateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeOwnerCertificateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'certificate': json['certificate'],
    };
}

export function NodeOwnerCertificateResponseToJSON(value?: NodeOwnerCertificateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'certificate': value.certificate,
    };
}

