/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OutputID
 */
export interface OutputID {
    /**
     * The output ID
     * @type {string}
     * @memberof OutputID
     */
    outputId: string;
}

/**
 * Check if a given object implements the OutputID interface.
 */
export function instanceOfOutputID(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "outputId" in value;

    return isInstance;
}

export function OutputIDFromJSON(json: any): OutputID {
    return OutputIDFromJSONTyped(json, false);
}

export function OutputIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputID {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'outputId': json['outputId'],
    };
}

export function OutputIDToJSON(value?: OutputID | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'outputId': value.outputId,
    };
}

