/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 123
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RentStructure } from './RentStructure';
import {
    RentStructureFromJSON,
    RentStructureFromJSONTyped,
    RentStructureToJSON,
} from './RentStructure';

/**
 * 
 * @export
 * @interface ProtocolParameters
 */
export interface ProtocolParameters {
    /**
     * The human readable network prefix
     * @type {string}
     * @memberof ProtocolParameters
     */
    bech32Hrp?: string;
    /**
     * The networks max depth
     * @type {number}
     * @memberof ProtocolParameters
     */
    belowMaxDepth?: number;
    /**
     * The minimal PoW score
     * @type {number}
     * @memberof ProtocolParameters
     */
    minPowScore?: number;
    /**
     * The network name
     * @type {string}
     * @memberof ProtocolParameters
     */
    networkName?: string;
    /**
     * 
     * @type {RentStructure}
     * @memberof ProtocolParameters
     */
    rentStructure?: RentStructure;
    /**
     * The token supply
     * @type {number}
     * @memberof ProtocolParameters
     */
    tokenSupply?: number;
    /**
     * The protocol version
     * @type {number}
     * @memberof ProtocolParameters
     */
    version?: number;
}

/**
 * Check if a given object implements the ProtocolParameters interface.
 */
export function instanceOfProtocolParameters(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProtocolParametersFromJSON(json: any): ProtocolParameters {
    return ProtocolParametersFromJSONTyped(json, false);
}

export function ProtocolParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProtocolParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bech32Hrp': !exists(json, 'bech32Hrp') ? undefined : json['bech32Hrp'],
        'belowMaxDepth': !exists(json, 'belowMaxDepth') ? undefined : json['belowMaxDepth'],
        'minPowScore': !exists(json, 'minPowScore') ? undefined : json['minPowScore'],
        'networkName': !exists(json, 'networkName') ? undefined : json['networkName'],
        'rentStructure': !exists(json, 'rentStructure') ? undefined : RentStructureFromJSON(json['rentStructure']),
        'tokenSupply': !exists(json, 'tokenSupply') ? undefined : json['tokenSupply'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function ProtocolParametersToJSON(value?: ProtocolParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bech32Hrp': value.bech32Hrp,
        'belowMaxDepth': value.belowMaxDepth,
        'minPowScore': value.minPowScore,
        'networkName': value.networkName,
        'rentStructure': RentStructureToJSON(value.rentStructure),
        'tokenSupply': value.tokenSupply,
        'version': value.version,
    };
}

