/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StateTransaction } from './StateTransaction';
import {
    StateTransactionFromJSON,
    StateTransactionFromJSONTyped,
    StateTransactionToJSON,
} from './StateTransaction';

/**
 * 
 * @export
 * @interface PublisherStateTransactionItem
 */
export interface PublisherStateTransactionItem {
    /**
     * 
     * @type {StateTransaction}
     * @memberof PublisherStateTransactionItem
     */
    lastMessage: StateTransaction;
    /**
     * 
     * @type {number}
     * @memberof PublisherStateTransactionItem
     */
    messages: number;
    /**
     * 
     * @type {Date}
     * @memberof PublisherStateTransactionItem
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the PublisherStateTransactionItem interface.
 */
export function instanceOfPublisherStateTransactionItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lastMessage" in value;
    isInstance = isInstance && "messages" in value;
    isInstance = isInstance && "timestamp" in value;

    return isInstance;
}

export function PublisherStateTransactionItemFromJSON(json: any): PublisherStateTransactionItem {
    return PublisherStateTransactionItemFromJSONTyped(json, false);
}

export function PublisherStateTransactionItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublisherStateTransactionItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastMessage': StateTransactionFromJSON(json['lastMessage']),
        'messages': json['messages'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function PublisherStateTransactionItemToJSON(value?: PublisherStateTransactionItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastMessage': StateTransactionToJSON(value.lastMessage),
        'messages': value.messages,
        'timestamp': (value.timestamp.toISOString()),
    };
}

