/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ratio32
 */
export interface Ratio32 {
    /**
     * 
     * @type {number}
     * @memberof Ratio32
     */
    a: number;
    /**
     * 
     * @type {number}
     * @memberof Ratio32
     */
    b: number;
}

/**
 * Check if a given object implements the Ratio32 interface.
 */
export function instanceOfRatio32(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a" in value;
    isInstance = isInstance && "b" in value;

    return isInstance;
}

export function Ratio32FromJSON(json: any): Ratio32 {
    return Ratio32FromJSONTyped(json, false);
}

export function Ratio32FromJSONTyped(json: any, ignoreDiscriminator: boolean): Ratio32 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a': json['a'],
        'b': json['b'],
    };
}

export function Ratio32ToJSON(value?: Ratio32 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a': value.a,
        'b': value.b,
    };
}

