/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 123
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestIDsResponse
 */
export interface RequestIDsResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof RequestIDsResponse
     */
    requestIds?: Array<string>;
}

/**
 * Check if a given object implements the RequestIDsResponse interface.
 */
export function instanceOfRequestIDsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestIDsResponseFromJSON(json: any): RequestIDsResponse {
    return RequestIDsResponseFromJSONTyped(json, false);
}

export function RequestIDsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestIDsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestIds': !exists(json, 'requestIds') ? undefined : json['requestIds'],
    };
}

export function RequestIDsResponseToJSON(value?: RequestIDsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'requestIds': value.requestIds,
    };
}

