/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestIDResponse
 */
export interface RequestIDResponse {
    /**
     * The request ID of the given transaction ID. (Hex)
     * @type {string}
     * @memberof RequestIDResponse
     */
    requestId: string;
}

/**
 * Check if a given object implements the RequestIDResponse interface.
 */
export function instanceOfRequestIDResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "requestId" in value;

    return isInstance;
}

export function RequestIDResponseFromJSON(json: any): RequestIDResponse {
    return RequestIDResponseFromJSONTyped(json, false);
}

export function RequestIDResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestIDResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestId': json['requestId'],
    };
}

export function RequestIDResponseToJSON(value?: RequestIDResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'requestId': value.requestId,
    };
}

