/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TxInclusionStateMsg
 */
export interface TxInclusionStateMsg {
    /**
     * The inclusion state
     * @type {string}
     * @memberof TxInclusionStateMsg
     */
    state: string;
    /**
     * The transaction ID
     * @type {string}
     * @memberof TxInclusionStateMsg
     */
    txId: string;
}

/**
 * Check if a given object implements the TxInclusionStateMsg interface.
 */
export function instanceOfTxInclusionStateMsg(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "txId" in value;

    return isInstance;
}

export function TxInclusionStateMsgFromJSON(json: any): TxInclusionStateMsg {
    return TxInclusionStateMsgFromJSONTyped(json, false);
}

export function TxInclusionStateMsgFromJSONTyped(json: any, ignoreDiscriminator: boolean): TxInclusionStateMsg {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'state': json['state'],
        'txId': json['txId'],
    };
}

export function TxInclusionStateMsgToJSON(value?: TxInclusionStateMsg | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'state': value.state,
        'txId': value.txId,
    };
}

