/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { L1Params } from './L1Params';
import {
    L1ParamsFromJSON,
    L1ParamsFromJSONTyped,
    L1ParamsToJSON,
} from './L1Params';

/**
 * 
 * @export
 * @interface InfoResponse
 */
export interface InfoResponse {
    /**
     * 
     * @type {L1Params}
     * @memberof InfoResponse
     */
    l1Params?: L1Params;
    /**
     * The net id of the node
     * @type {string}
     * @memberof InfoResponse
     */
    netID?: string;
    /**
     * The public key of the node
     * @type {string}
     * @memberof InfoResponse
     */
    publicKey?: string;
    /**
     * The version of the node
     * @type {string}
     * @memberof InfoResponse
     */
    version?: string;
}

/**
 * Check if a given object implements the InfoResponse interface.
 */
export function instanceOfInfoResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InfoResponseFromJSON(json: any): InfoResponse {
    return InfoResponseFromJSONTyped(json, false);
}

export function InfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'l1Params': !exists(json, 'l1Params') ? undefined : L1ParamsFromJSON(json['l1Params']),
        'netID': !exists(json, 'netID') ? undefined : json['netID'],
        'publicKey': !exists(json, 'publicKey') ? undefined : json['publicKey'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function InfoResponseToJSON(value?: InfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'l1Params': L1ParamsToJSON(value.l1Params),
        'netID': value.netID,
        'publicKey': value.publicKey,
        'version': value.version,
    };
}

