/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NodeConnectionMessageMetrics } from './NodeConnectionMessageMetrics';
import {
    NodeConnectionMessageMetricsFromJSON,
    NodeConnectionMessageMetricsFromJSONTyped,
    NodeConnectionMessageMetricsToJSON,
} from './NodeConnectionMessageMetrics';

/**
 * 
 * @export
 * @interface NodeConnectionMessagesMetrics
 */
export interface NodeConnectionMessagesMetrics {
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMessagesMetrics
     */
    inAliasOutput?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMessagesMetrics
     */
    inOnLedgerRequest?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMessagesMetrics
     */
    inOutput?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMessagesMetrics
     */
    inStateOutput?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMessagesMetrics
     */
    inTxInclusionState?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMessagesMetrics
     */
    outPublishGovernanceTransaction?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMessagesMetrics
     */
    outPublishStateTransaction?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMessagesMetrics
     */
    outPullLatestOutput?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMessagesMetrics
     */
    outPullOutputByID?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMessagesMetrics
     */
    outPullTxInclusionState?: NodeConnectionMessageMetrics;
}

/**
 * Check if a given object implements the NodeConnectionMessagesMetrics interface.
 */
export function instanceOfNodeConnectionMessagesMetrics(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NodeConnectionMessagesMetricsFromJSON(json: any): NodeConnectionMessagesMetrics {
    return NodeConnectionMessagesMetricsFromJSONTyped(json, false);
}

export function NodeConnectionMessagesMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeConnectionMessagesMetrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inAliasOutput': !exists(json, 'inAliasOutput') ? undefined : NodeConnectionMessageMetricsFromJSON(json['inAliasOutput']),
        'inOnLedgerRequest': !exists(json, 'inOnLedgerRequest') ? undefined : NodeConnectionMessageMetricsFromJSON(json['inOnLedgerRequest']),
        'inOutput': !exists(json, 'inOutput') ? undefined : NodeConnectionMessageMetricsFromJSON(json['inOutput']),
        'inStateOutput': !exists(json, 'inStateOutput') ? undefined : NodeConnectionMessageMetricsFromJSON(json['inStateOutput']),
        'inTxInclusionState': !exists(json, 'inTxInclusionState') ? undefined : NodeConnectionMessageMetricsFromJSON(json['inTxInclusionState']),
        'outPublishGovernanceTransaction': !exists(json, 'outPublishGovernanceTransaction') ? undefined : NodeConnectionMessageMetricsFromJSON(json['outPublishGovernanceTransaction']),
        'outPublishStateTransaction': !exists(json, 'outPublishStateTransaction') ? undefined : NodeConnectionMessageMetricsFromJSON(json['outPublishStateTransaction']),
        'outPullLatestOutput': !exists(json, 'outPullLatestOutput') ? undefined : NodeConnectionMessageMetricsFromJSON(json['outPullLatestOutput']),
        'outPullOutputByID': !exists(json, 'outPullOutputByID') ? undefined : NodeConnectionMessageMetricsFromJSON(json['outPullOutputByID']),
        'outPullTxInclusionState': !exists(json, 'outPullTxInclusionState') ? undefined : NodeConnectionMessageMetricsFromJSON(json['outPullTxInclusionState']),
    };
}

export function NodeConnectionMessagesMetricsToJSON(value?: NodeConnectionMessagesMetrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'inAliasOutput': NodeConnectionMessageMetricsToJSON(value.inAliasOutput),
        'inOnLedgerRequest': NodeConnectionMessageMetricsToJSON(value.inOnLedgerRequest),
        'inOutput': NodeConnectionMessageMetricsToJSON(value.inOutput),
        'inStateOutput': NodeConnectionMessageMetricsToJSON(value.inStateOutput),
        'inTxInclusionState': NodeConnectionMessageMetricsToJSON(value.inTxInclusionState),
        'outPublishGovernanceTransaction': NodeConnectionMessageMetricsToJSON(value.outPublishGovernanceTransaction),
        'outPublishStateTransaction': NodeConnectionMessageMetricsToJSON(value.outPublishStateTransaction),
        'outPullLatestOutput': NodeConnectionMessageMetricsToJSON(value.outPullLatestOutput),
        'outPullOutputByID': NodeConnectionMessageMetricsToJSON(value.outPullOutputByID),
        'outPullTxInclusionState': NodeConnectionMessageMetricsToJSON(value.outPullTxInclusionState),
    };
}

