/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeConnectionMessageMetrics
 */
export interface NodeConnectionMessageMetrics {
    /**
     * Last time the message was sent/received
     * @type {Date}
     * @memberof NodeConnectionMessageMetrics
     */
    lastEvent?: Date;
    /**
     * The print out of the last message
     * @type {string}
     * @memberof NodeConnectionMessageMetrics
     */
    lastMessage?: string;
    /**
     * Total number of messages sent/received
     * @type {number}
     * @memberof NodeConnectionMessageMetrics
     */
    total?: number;
}

/**
 * Check if a given object implements the NodeConnectionMessageMetrics interface.
 */
export function instanceOfNodeConnectionMessageMetrics(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NodeConnectionMessageMetricsFromJSON(json: any): NodeConnectionMessageMetrics {
    return NodeConnectionMessageMetricsFromJSONTyped(json, false);
}

export function NodeConnectionMessageMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeConnectionMessageMetrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastEvent': !exists(json, 'lastEvent') ? undefined : (new Date(json['lastEvent'])),
        'lastMessage': !exists(json, 'lastMessage') ? undefined : json['lastMessage'],
        'total': !exists(json, 'total') ? undefined : json['total'],
    };
}

export function NodeConnectionMessageMetricsToJSON(value?: NodeConnectionMessageMetrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastEvent': value.lastEvent === undefined ? undefined : (value.lastEvent.toISOString()),
        'lastMessage': value.lastMessage,
        'total': value.total,
    };
}

