/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NodeConnectionMessageMetrics } from './NodeConnectionMessageMetrics';
import {
    NodeConnectionMessageMetricsFromJSON,
    NodeConnectionMessageMetricsFromJSONTyped,
    NodeConnectionMessageMetricsToJSON,
} from './NodeConnectionMessageMetrics';

/**
 * 
 * @export
 * @interface NodeConnectionMetrics
 */
export interface NodeConnectionMetrics {
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMetrics
     */
    inAliasOutput?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMetrics
     */
    inMilestone?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMetrics
     */
    inOnLedgerRequest?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMetrics
     */
    inOutput?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMetrics
     */
    inStateOutput?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMetrics
     */
    inTxInclusionState?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMetrics
     */
    outPublishGovernanceTransaction?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMetrics
     */
    outPublishStateTransaction?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMetrics
     */
    outPullLatestOutput?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMetrics
     */
    outPullOutputByID?: NodeConnectionMessageMetrics;
    /**
     * 
     * @type {NodeConnectionMessageMetrics}
     * @memberof NodeConnectionMetrics
     */
    outPullTxInclusionState?: NodeConnectionMessageMetrics;
    /**
     * Chain IDs of the chains registered to receiving L1 events
     * @type {Array<string>}
     * @memberof NodeConnectionMetrics
     */
    registered?: Array<string>;
}

/**
 * Check if a given object implements the NodeConnectionMetrics interface.
 */
export function instanceOfNodeConnectionMetrics(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NodeConnectionMetricsFromJSON(json: any): NodeConnectionMetrics {
    return NodeConnectionMetricsFromJSONTyped(json, false);
}

export function NodeConnectionMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeConnectionMetrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inAliasOutput': !exists(json, 'InAliasOutput') ? undefined : NodeConnectionMessageMetricsFromJSON(json['InAliasOutput']),
        'inMilestone': !exists(json, 'InMilestone') ? undefined : NodeConnectionMessageMetricsFromJSON(json['InMilestone']),
        'inOnLedgerRequest': !exists(json, 'InOnLedgerRequest') ? undefined : NodeConnectionMessageMetricsFromJSON(json['InOnLedgerRequest']),
        'inOutput': !exists(json, 'InOutput') ? undefined : NodeConnectionMessageMetricsFromJSON(json['InOutput']),
        'inStateOutput': !exists(json, 'InStateOutput') ? undefined : NodeConnectionMessageMetricsFromJSON(json['InStateOutput']),
        'inTxInclusionState': !exists(json, 'InTxInclusionState') ? undefined : NodeConnectionMessageMetricsFromJSON(json['InTxInclusionState']),
        'outPublishGovernanceTransaction': !exists(json, 'OutPublishGovernanceTransaction') ? undefined : NodeConnectionMessageMetricsFromJSON(json['OutPublishGovernanceTransaction']),
        'outPublishStateTransaction': !exists(json, 'OutPublishStateTransaction') ? undefined : NodeConnectionMessageMetricsFromJSON(json['OutPublishStateTransaction']),
        'outPullLatestOutput': !exists(json, 'OutPullLatestOutput') ? undefined : NodeConnectionMessageMetricsFromJSON(json['OutPullLatestOutput']),
        'outPullOutputByID': !exists(json, 'OutPullOutputByID') ? undefined : NodeConnectionMessageMetricsFromJSON(json['OutPullOutputByID']),
        'outPullTxInclusionState': !exists(json, 'OutPullTxInclusionState') ? undefined : NodeConnectionMessageMetricsFromJSON(json['OutPullTxInclusionState']),
        'registered': !exists(json, 'Registered') ? undefined : json['Registered'],
    };
}

export function NodeConnectionMetricsToJSON(value?: NodeConnectionMetrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'InAliasOutput': NodeConnectionMessageMetricsToJSON(value.inAliasOutput),
        'InMilestone': NodeConnectionMessageMetricsToJSON(value.inMilestone),
        'InOnLedgerRequest': NodeConnectionMessageMetricsToJSON(value.inOnLedgerRequest),
        'InOutput': NodeConnectionMessageMetricsToJSON(value.inOutput),
        'InStateOutput': NodeConnectionMessageMetricsToJSON(value.inStateOutput),
        'InTxInclusionState': NodeConnectionMessageMetricsToJSON(value.inTxInclusionState),
        'OutPublishGovernanceTransaction': NodeConnectionMessageMetricsToJSON(value.outPublishGovernanceTransaction),
        'OutPublishStateTransaction': NodeConnectionMessageMetricsToJSON(value.outPublishStateTransaction),
        'OutPullLatestOutput': NodeConnectionMessageMetricsToJSON(value.outPullLatestOutput),
        'OutPullOutputByID': NodeConnectionMessageMetricsToJSON(value.outPullOutputByID),
        'OutPullTxInclusionState': NodeConnectionMessageMetricsToJSON(value.outPullTxInclusionState),
        'Registered': value.registered,
    };
}

