/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Output } from './Output';
import {
    OutputFromJSON,
    OutputFromJSONTyped,
    OutputToJSON,
} from './Output';

/**
 * 
 * @export
 * @interface OnLedgerRequest
 */
export interface OnLedgerRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof OnLedgerRequest
     */
    bytes?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof OnLedgerRequest
     */
    iD?: string;
    /**
     * 
     * @type {Output}
     * @memberof OnLedgerRequest
     */
    output?: Output;
    /**
     * 
     * @type {string}
     * @memberof OnLedgerRequest
     */
    outputID?: string;
}

/**
 * Check if a given object implements the OnLedgerRequest interface.
 */
export function instanceOfOnLedgerRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OnLedgerRequestFromJSON(json: any): OnLedgerRequest {
    return OnLedgerRequestFromJSONTyped(json, false);
}

export function OnLedgerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnLedgerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bytes': !exists(json, 'Bytes') ? undefined : json['Bytes'],
        'iD': !exists(json, 'ID') ? undefined : json['ID'],
        'output': !exists(json, 'Output') ? undefined : OutputFromJSON(json['Output']),
        'outputID': !exists(json, 'OutputID') ? undefined : json['OutputID'],
    };
}

export function OnLedgerRequestToJSON(value?: OnLedgerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Bytes': value.bytes,
        'ID': value.iD,
        'Output': OutputToJSON(value.output),
        'OutputID': value.outputID,
    };
}

