/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Output
 */
export interface Output {
    /**
     * 
     * @type {Array<number>}
     * @memberof Output
     */
    bytes?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof Output
     */
    outputType?: number;
}

/**
 * Check if a given object implements the Output interface.
 */
export function instanceOfOutput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OutputFromJSON(json: any): Output {
    return OutputFromJSONTyped(json, false);
}

export function OutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): Output {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bytes': !exists(json, 'Bytes') ? undefined : json['Bytes'],
        'outputType': !exists(json, 'OutputType') ? undefined : json['OutputType'],
    };
}

export function OutputToJSON(value?: Output | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Bytes': value.bytes,
        'OutputType': value.outputType,
    };
}

