/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PeeringTrustedNode
 */
export interface PeeringTrustedNode {
    /**
     * NetID of a peer to trust.
     * @type {string}
     * @memberof PeeringTrustedNode
     */
    netId?: string;
    /**
     * Public key of the NetID.
     * @type {string}
     * @memberof PeeringTrustedNode
     */
    pubKey?: string;
}

/**
 * Check if a given object implements the PeeringTrustedNode interface.
 */
export function instanceOfPeeringTrustedNode(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PeeringTrustedNodeFromJSON(json: any): PeeringTrustedNode {
    return PeeringTrustedNodeFromJSONTyped(json, false);
}

export function PeeringTrustedNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeeringTrustedNode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'netId': !exists(json, 'netId') ? undefined : json['netId'],
        'pubKey': !exists(json, 'pubKey') ? undefined : json['pubKey'],
    };
}

export function PeeringTrustedNodeToJSON(value?: PeeringTrustedNode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'netId': value.netId,
        'pubKey': value.pubKey,
    };
}

