/* tslint:disable */
/* eslint-disable */
/**
 * Wasp API
 * REST API for the Wasp node
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestProcessedResponse
 */
export interface RequestProcessedResponse {
    /**
     * 
     * @type {string}
     * @memberof RequestProcessedResponse
     */
    chainID?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RequestProcessedResponse
     */
    isProcessed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RequestProcessedResponse
     */
    requestID?: string;
}

/**
 * Check if a given object implements the RequestProcessedResponse interface.
 */
export function instanceOfRequestProcessedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestProcessedResponseFromJSON(json: any): RequestProcessedResponse {
    return RequestProcessedResponseFromJSONTyped(json, false);
}

export function RequestProcessedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestProcessedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chainID': !exists(json, 'ChainID') ? undefined : json['ChainID'],
        'isProcessed': !exists(json, 'IsProcessed') ? undefined : json['IsProcessed'],
        'requestID': !exists(json, 'RequestID') ? undefined : json['RequestID'],
    };
}

export function RequestProcessedResponseToJSON(value?: RequestProcessedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ChainID': value.chainID,
        'IsProcessed': value.isProcessed,
        'RequestID': value.requestID,
    };
}

